#!/bin/bash

### * dream1986 *
### 使用zenity给you-get在线视频下载软件创建交互式图形窗口
### 需要安装 zenity 、you-get 、lxterminal (可用其他终端替换)


### 定义下载目录
dir=/home/dream/视频/

### 创建在线视频地址提交窗口,获取视频url地址,按取消键退出
url=$(zenity --entry --title="you-get 视频下载" --text="输入在线视频地址：" --width=500)
if [[ $? == 1 ]] ;
then
	exit
fi


### 打开一个新lxterminal窗口显示进度
lxterminal --title="you-get 正在下载视频：" -e you-get -o ${dir} ${url}
