#!/bin/bash

### * dream1986 *  20151216
### 使用zenity给you-get在线视频下载软件创建交互式图形窗口
### 需要安装 zenity 、you-get 、lxterminal (可用其他终端替换)
### 将这个脚本绑定键盘快捷键，使用时复制视频地址，按快捷键调出(窗口1), 粘贴视频地址点确定


### 定义下载目录
dir=/home/dream/视频/

### 创建在线视频地址提交窗口,获取视频url地址,按确定键开始下载，按取消键退出 (窗口1)
url=$(zenity --entry --title="you-get 视频下载" --text="输入在线视频地址：" --width=500)
if [[ $? == 1 ]] ;
then
	exit
fi


### 打开一个新lxterminal窗口显示进度
lxterminal --title="you-get 正在下载视频：" -e you-get -o ${dir} ${url}
